version: "3.9"

services:
  database:
    image: postgres
    container_name: kindheart_api
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kindheart_db
    volumes:
      - pgdata:/data/postgres
      
volumes:
  pgdata: